- frontend/index.html
- frontend/script.js
- frontend/style.css
-Redesigned the entire index.html file
-Improved structure, added sections and styling hooks
-Prepared layout for animations and features
> Updated index.html layout and design

- frontend/login.html
Uploaded html code for login page
> added login.html page

- frontend/signup.css
- frontend/signup.html
- frontend/signup.js
-Added new files signup.html signup.css signup.js
> Added new files signup.html signup.css and sign.js in frontend

- todo.html
> Added todo.html with updated tasks

- frontend/404.html
- frontend/style.css
uploaded html code for scm project
- in error-page -
> uploaded 404.html 

- frontend/analytics.css
- frontend/analytics.html
-uploaded code for scm project -
> Added new files analytics.html analytics.css in frontend

- frontend/settings.css
- frontend/settings.html
- frontend/settings.js
-Added settings.html
-Added settings.css
-Added settings.html
> Added new files settings.html settings.css settings.js

- frontend/index.html
-Changed the layout of homepage
-Make some changes in section, header and footer
> Modified the layout of homepage and add new sections

- frontend/404.html
- frontend/404.js
> added 404.js updated 404.html to frontend

- frontend/collaboration.css
- frontend/collaboration.html
- frontend/collaboration.js
-uploaded html code for SCM project
-good layout...
> Added collaboration.html collaboration.css collaboration.js to frontend

- frontend/contact.css
- frontend/contact.html
-uploaded html for SCM project
-good layout...
> Added contact.html contact.css to frontend

- dashboard.html
-uploaded html code for SCM project
-good layout...
> added dashboard.html to frontend

- frontend/index.html
- frontend/style.css
-Added new sections in homepage.
-Updated the style.css
> Index overhaul

- frontend/login.css
Uploaded login files for scm project
> Login dashboard

- frontend/signup.css
- frontend/signup.html
- frontend/signup.js
-Modified signup page.
-Updated HTML structure.
-Improved styling,
-Enhanced JS validation
> Updated the code of signup.html signup.css signup.js

- frontend/pomodoro.css
- frontend/pomodoro.html
- frontend/pomodoro.js
-Updated HTML structure for better layout and responsiveness.
-Enhanced CSS for a more aesthetic and modern look.
-Improved JavaScript logic for accurate countdown and reset behavior
> Modified pomodoro UI and functionality in HTML, CSS, and JS

- frontend/todo.css
added css code to the todo list
> added css to todo list

- frontend/story-detail.css
- frontend/story-detail.html
> Added story-detail.html story-detail.css to frontend

- frontend/tasks.css
- frontend/tasks.html
- frontend/tasks.js
> added tasks.html tasks.css tasks.js to frontend

- analytics.js
> added analytics.js to frontend

- frontend/story-detail.js
> Added story-detail.js to frontend

- frontend/calendar.html
-Added new file of calendar.html
> Added new file calendar.html

- dashboard.css
- dashboard.js
added css and js file to dashboard
> added css and js file to dashboard

- frontend/addtomytasks.css
- frontend/addtomytasks.html
- frontend/addtomytasks.js
> Added 3 new files addtomytasks.html addtomytasks.css addtomytasks.js

- frontend/story-detail.css
- frontend/story-detail.html
- frontend/story-detail.js
> Updated story-detail files to frontend

- frontend/privacy.css
- frontend/privacy.html
- frontend/privacy.js
> updated privacy files to frontend

- frontend/about.css
- frontend/about.html
> Updated about-page to frontend

- frontend/analytics.css
- frontend/analytics.html
- frontend/analytics.js
> updated analytics files to frontend

- frontend/achievements.css
- frontend/achievements.html
- frontend/achievements.js
> added achievements files to frontend

- frontend/dashboard.html
> updated dashboard files to frontend

- frontend/collaboration.css
- frontend/collaboration.js
> updated collaboration files to frontend

- frontend/tasks.css
> updated tasks files

- frontend/Blog-post1.css
- frontend/Blog-post1.js
> Updated Blog-Post1 files to frontend

- frontend/about.html
> Updated code in frontend
